package coyni.api.business.popups;

import org.openqa.selenium.By;

import coyni.admin.components.AuthyComponent;
import coyni.customer.components.NavigationComponent;
import coyni.uitilities.CommonFunctions;
import ilabs.WebFramework.BrowserFunctions;

public class EmailAddressAuthenticationPopup extends BrowserFunctions {

	private By lblEmailAddressAuth = By.xpath("//h1[text()='Edit Email Address']");
	private By descEmailAddressAuth = By
			.xpath("//span[contains(text(),'Please enter the code generated by your authentication app')]");

	public NavigationComponent navigationComponent() {
		return new NavigationComponent();
	}

	public AuthyComponent authyComponent() {
		return new AuthyComponent();
	}

	public void verifyEmailAddressAuthHeading(String expEmailAddressHeading) {
		new CommonFunctions().verifyLabelText(lblEmailAddressAuth, "Email Address Authentication Heading is",
				expEmailAddressHeading);
	}

	public void verifyEmailAddressDescHeading(String expEmailAddressDescHeading) {
		new CommonFunctions().verifyLabelText(descEmailAddressAuth,
				"Email Address Description  Authentication Heading is", expEmailAddressDescHeading);
	}

}
